version: '3.1'
services:
  mongo:
    image: mongo:4.4.27-rc0-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  product-webflux:
    build:
      context: ..
      dockerfile: devops/Dockerfile
    image: product-webflux:1.0
    environment:
      MONGODB_URI: mongodb://root:example@mongo:27017/store-db?authSource=admin
    ports:
      - "9090:8090"
    depends_on:
      - mongo
  product-webflux-client:
    image: product-webflux-client:1.0
    environment:
      PRODUCT_URI: http://product-webflux:8090
      PRODUCT_API-KEY: product-webflux-api-key
    ports:
      - "9095:8095"
    depends_on:
      - product-webflux